language: cpp
sudo: required

addons:
  apt:
    sources:
    - sourceline: "ppa:openmw/openmw"
    packages:
    - libgtest-dev
    - libopenscenegraph-3.4-dev
    - libspdlog-cpp-dev

install:
  - cd /usr/src/gtest
  - sudo $(which cmake) .
  - sudo $(which make)
  - sudo mv libgtest* /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
